test:
	scam -r task3.scm tests/task3.0
	scam -r task3.scm tests/task3.1
	scam -r task3.scm tests/task3.2
	scam -r task3.scm tests/task3.3
	scam -r task3.scm tests/task3.4
	scam -r task3.scm tests/task3.5
	scam -r task3.scm tests/task3.6
	scam -r task3.scm tests/task3.7
	scam -r task3.scm tests/task3.8
	scam -r task3.scm tests/task3.9
	scam -r task4.scm tests/task4.0
	scam -r task4.scm tests/task4.1
	scam -r task4.scm tests/task4.2
	scam -r task4.scm tests/task4.3
	scam -r task4.scm tests/task4.4
	scam -r task4.scm tests/task4.5
	scam -r task6.scm tests/task6.9
