(define (curry f @)
    (define nparams (length (get 'parameters f)))
    (define givens @)
    (define (helper source store)          
        (cond
            ((= store nparams)
                (apply f givens)
            )
            ((not (valid? source))
                (lambda (@)
                    (define new-params 
                        (cond 
                            ((nil? givens) (flatten @))
                            (else (flatten (list givens @)))
                        )
                    )
                    (cond 
                        ((= nparams (length new-params))
                            (apply f new-params)
                        )
                        (else (curry f new-params))
                    )
                )
            ) 
            (else
                (helper (cdr source) (+ store 1))    
            )
        )
    )
    (helper givens 0)
)

(define (flatten list)
  (cond 
        ((nil? list) nil)
        ((pair? (car list))
            (append (flatten (car list))
                    (flatten (cdr list))
            )
        )
        (else (cons (car list) (flatten (cdr list))))
    )
)


(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (define (iter expr)
        (if (not (eof?)) 
            (begin (eval expr env) (iter (readExpr)))
        )
    )
    (iter (readExpr))    
)