(define (powerSet set)
    (inspect set)
    (inspect (car set))
    (inspect (cdr set))
    ;(list nil (list (car set)) (list (cadr set)) set)
    (define (helper source store)
        (cond 
            ((nil? source) store)
        )
    )
    (helper set nil)
)

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (setNilDisplay 'nil)
    (define (iter expr)
        (if (not (eof?)) 
            (begin (eval expr env) (iter (readExpr)))
        )
    )
    (iter (readExpr))    
)