(define (replace f list)
    (define code (cadr (get 'code f)))
    (check-replace code list)
)

(define (check-replace line vars)
    (inspect line)
    (inspect vars)
)

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (define (iter expr)
        (if (not (eof?)) 
            (begin (eval expr env) (iter (readExpr)))
        )
    )
    (iter (readExpr))    
)