(define (check-builtin obj sym)
    'oof
)

(define (scoping sym obj)
    ; (ppTable obj)
    (define vars (cadr obj))
    ; (inspect vars)
    (define start (cdddddr vars))
    (define (helper source)
        (cond
            ((nil? source) (check-builtin obj sym))
            ((eq? (car source) sym) 'bound)
            (else (helper (cdr source)))
        )
    )
    (helper start)
)
(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (define (iter expr)
        (if (not (eof?)) 
            (begin (eval expr env) (iter (readExpr)))
        )
    )
    (iter (readExpr))    
)